version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: student09
      POSTGRES_PASSWORD: mF2gT0pO6bV4wJ5m
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      # Mount both task_1 and task_2 directories
      - ./homework_1/task_1:/scripts/task_1
      - ./homework_1/task_2:/scripts/task_2
      - ./homework_3/task_4:/scripts/task_4
    restart: always

volumes:
  postgres_data: